App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name="blog_list"),
    path('write/', views.CreateBlog.as_view(), name="create_blog"),
    path('details/<slug:slug>/', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name="my_blogs"),
    path('edit/<pk>', views.UpdateBlog.as_view(), name="edit_blog"),

]

App_Login/urls.py
from django.urls import path
from . import views


app_name="App_Login"

urlpatterns = [
    path("signup/", views.sign_up, name='signup'),
    path("login/", views.login_page, name='login'),
    path("logout/", views.logout_user, name='logout'),
    path("profile/", views.profile, name='profile'),
    path("change_profile/", views.user_change, name='change_profile'),
    path("password/", views.pass_change, name='pass_change'),
    path("add-pictures/", views.add_pro_pic, name='add_pro_pic'),
    path("change-pictures/", views.change_pro_pic, name='change_pro_pic'),
]

My_Blog/urls.py

from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name="index"),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title_block %}Blogs{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}"><img src="/media/logo.png" width="100px"></a>
      </li>
        {% if user.is_authenticated %}
         <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">@{{user.username}} </a>
        <div class="dropdown-menu">
         </li><li class="nav-item ">
        <a class="nav-link" href="{% url 'App_Blog:create_blog' %}">Write Blog </a>
      </li>
            <li class="nav-item ">
        <a class="nav-link" href="{% url 'App_Blog:my_blogs' %}">My Blogs </a>
      </li>
        </li><li class="nav-item ">
        <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile </a>
            <hr>
        </li>
            <li class="nav-item ">
        <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout </a>
      </li>
        </div>

        {% else %}
        <li class="nav-item ">
        <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up </a>

        <li class="nav-item ">
        <a class="nav-link" href="{% url 'App_Login:login' %}">Login </a>
      </li>
       {% endif%}

    </ul>

</nav>

<div class="container pt-20">
    {% block body_block %}
    {% endblock %}
</div>


</body>
</html>